#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Example.Shared.Application.Droid.Resource", IsApplication=true)]

namespace Example.Shared.Application.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public const int adSize = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int adSizes = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int adUnitId = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010016
			public const int circleCrop = 2130771990;
			
			// aapt resource value: 0x7f010015
			public const int imageAspectRatio = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int imageAspectRatioAdjust = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080009
			public const int common_action_bar_splitter = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int common_signin_btn_dark_text_default = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int common_signin_btn_dark_text_disabled = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int common_signin_btn_dark_text_focused = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int common_signin_btn_dark_text_pressed = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int common_signin_btn_default_background = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int common_signin_btn_light_text_default = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int common_signin_btn_light_text_disabled = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int common_signin_btn_light_text_focused = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int common_signin_btn_light_text_pressed = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int common_signin_btn_text_dark = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int common_signin_btn_text_light = 2131230731;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_os_notification_fallback_white_24dp = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int powered_by_google_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int powered_by_google_light = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int myButton = 2131361799;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int os_bgimage_notif_bgimage = 2131361800;
			
			// aapt resource value: 0x7f0a000a
			public const int os_bgimage_notif_body = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int os_bgimage_notif_title = 2131361801;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int google_play_services_version = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int onesignal_bgimage_notif_layout = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int gtm_analytics = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060004
			public const int accept = 2131099652;
			
			// aapt resource value: 0x7f060029
			public const int app_name = 2131099689;
			
			// aapt resource value: 0x7f060009
			public const int auth_google_play_services_client_facebook_display_name = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int auth_google_play_services_client_google_display_name = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int common_android_wear_notification_needs_update_text = 2131099660;
			
			// aapt resource value: 0x7f060019
			public const int common_android_wear_update_text = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int common_android_wear_update_title = 2131099671;
			
			// aapt resource value: 0x7f060025
			public const int common_google_play_services_api_unavailable_text = 2131099685;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_enable_button = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int common_google_play_services_enable_text = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_enable_title = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_error_notification_requested_by_msg = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_install_button = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_install_text_phone = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_install_text_tablet = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_install_title = 2131099663;
			
			// aapt resource value: 0x7f06001f
			public const int common_google_play_services_invalid_account_text = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_invalid_account_title = 2131099678;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_needs_enabling_title = 2131099661;
			
			// aapt resource value: 0x7f06001d
			public const int common_google_play_services_network_error_text = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int common_google_play_services_network_error_title = 2131099676;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_notification_needs_update_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_notification_ticker = 2131099658;
			
			// aapt resource value: 0x7f060027
			public const int common_google_play_services_sign_in_failed_text = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int common_google_play_services_sign_in_failed_title = 2131099686;
			
			// aapt resource value: 0x7f060020
			public const int common_google_play_services_unknown_issue = 2131099680;
			
			// aapt resource value: 0x7f060022
			public const int common_google_play_services_unsupported_text = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int common_google_play_services_unsupported_title = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int common_google_play_services_update_button = 2131099683;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_update_text = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_update_title = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_play_services_updating_text = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_play_services_updating_title = 2131099674;
			
			// aapt resource value: 0x7f060024
			public const int common_open_on_phone = 2131099684;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_button_text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_button_text_long = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int create_calendar_message = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int create_calendar_title = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int decline = 2131099653;
			
			// aapt resource value: 0x7f060028
			public const int hello = 2131099688;
			
			// aapt resource value: 0x7f060003
			public const int store_picture_message = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int store_picture_title = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_IAPTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
